apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UEtrRTum8jJft1x66Sp5toHItM8PYzjfba+Hbz4nHV/dMjxxsFK/Og==,iv:SmjK5gvIBOU8/29LKbo/86b8A479D9TbOswkTIjQ8X8=,tag:l0iHEN5REqs5+lzIqvUhTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOVBuYXF1c213UkdsNDlX
            K1NBSGdwTCtZVkZRT3RaalpsZDYvbHlYWjBBCjhMSWR2c2UrNER3Mi9nVmlvOEpZ
            NFhQaXlRbDk5QlJhZ2R5UVFVVXZnQUEKLS0tIEZHWXlCRGZUVXp4aDFPUlY5Y1o4
            bWRQNXMvajc0cENtOUtQSDJ6WXh3UFEKblcekT2XvPQTSAPAymWeensSK7thCriM
            Iniybaalzv5PFrDTZco07PvyTuKkAwCAoBN1bSFPXUVxyJnzfhShFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-20T00:55:20Z"
    mac: ENC[AES256_GCM,data:llCMEZhYgutLU61maI+g7qRF0FZnDi7ddjzxvfnCsGDfgYjRvyEEM9QP+M3Fq+5OHU40udzlr94bekUj00vZ3DIBFZea32IbP0PQphw1t0+Up4W/HogXuAuQZQL8P7t+EsjKxNj8uFt29rHAiI6By5HGSAGQtWILIhVVzVAoABE=,iv:e7WvZUe4fFHbprFIzREQv32/v/uSoLXBcy+Xl/mgSG8=,tag:m24wUBHflv1O4AUsTeFkGA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
