apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6z8glwyYgdb2PTR7FB1lSJslnzCadKBUTByXXEovg25u7kkFIFGHlw==,iv:myZu002zXlZ+3xZw6WE6YN44RM7OBH/rzRX5rbXI8A4=,tag:InU0d114WmKCDZPcvfblIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVlRDdVl3MVhIWjN3V251
            TThHUVNDYTIxc3lPbE13ZG9XbHhQQ0MxWlNJCmh5aHUwa1BrbGVXMDdVaHNwK2JJ
            VU1Wa2R0ZWFDMVE2UlNFOHh3Mm1JZUUKLS0tIHFjRHhYalc1TnBTaDF2dnFpV2dH
            ODBRMFpRL3RFa1JJM3padzNnd3ZvU1UKYR5kmRwyWazZirGtsVeS8jAU6k6Q6pJU
            GQ7QrA65kXJt1kT6sVw9Kb0YgLAeaWzP5Angpcr+CwkNVLbXZr3euw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-19T21:56:25Z"
    mac: ENC[AES256_GCM,data:7ADXXb9LFWqiNFxntpxpbvn5LtA+OCajmR9bVnaB3SqrSWwLRRrjaDUDNiAno/8aSHRGPLUZf5NpYePMrXVlNhBScB06JzEAK7PMg5hE43RWE3nYrDMUoElY6eZuetyoFoq6BBXq1SPqysR4+37Vhn/g/F9WKHzZAacTJE2/C4Y=,iv:hXCb2DWW6KG+qXpth8ZXiplrC+fGB9KXLO5gNdbMrHY=,tag:lcPofjlJmVZlgqSbILKEWA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
