apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3OTx/dsEi0zm6mthKcDUVI4J1r6nbucbZl1NOg+bG/wZjPkHiYM6Zw==,iv:x+j2qtmPsuatBeF7BVuQ/2ay3EtAdYijHCe3PYm/gyg=,tag:e5vpgjHuoYZbRDjEHzOmIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdFlvMnJSMmprRm10N1dp
            RmhpeGVobTlMdHJsUUtWcGo1L3RwcjlSWkVJCnMrd2UremxnTXhOUEJtd2JTbjF3
            V1pZUzZGOG1yR1ltajU2VUN3VFBSQU0KLS0tIC9FbmNsdDBqYXJHd09wY21IOTdV
            cG9weC9kd1dsSG1EZlRHU24xQzc2YWcK1nYqXkaNra6LeNS/NHweyDypPyq79HKI
            QewT/7aRZ1VgTicIg5mX345M5pJlbuTotcM/zDiLGN5uGtNO6Q3KPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-29T16:03:14Z"
    mac: ENC[AES256_GCM,data:+OmwuaftjOXEdQ73r5AMK6WhYNQwNiBEBG3Sf1tsf++rXh34wJmkRvn9QQX67EXILu/HecH4B50xFSX6aT1gISVlC1WXucyyLfKtLLs775HaDb6VNzuszbpXNMGDmBr92vgsx75Frg5q0d2DDhn1lFenNVaWu+N59LnpDCKLdUs=,iv:/HokueDKjLa9i+z4ChleIn7PQWFRE6FLu4A4n+bhVpo=,tag:SsnCO2nplBXhpikFF7W/JA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
