#!/bin/bash -e

if [ -z "$1" ]; then
  echo "Must specify a commit log"
  exit 2
fi

fakeClustertool() {
  sed -i.bak -e 's/v1\.12\.1/v1.11.3/' -e 's/v1\.35\.0/v1.34.3/' clusters/main/talos/talconfig.yaml
}
unfakeClustertool() {
  sed -i.bak -e 's/v1\.11\.3/v1.12.1/' -e 's/v1\.34\.3/v1.35.0/' clusters/main/talos/talconfig.yaml clusters/main/talos/generated/main-k8s-node-1.yaml
}

fakeClustertool
clustertool genconfig
unfakeClustertool

git add clusters repositories
clustertool encrypt
git commit -m "$1"
git pull
git push
clustertool decrypt
# sleep 1
# flux reconcile source git cluster -n flux-system
