apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:69o4KWZEeCoKenL+sVW0iqggdb5jRSaZ3RFx1vAhapUvhM7kWFQ5ytHX6GPEsHKEqIwrSqVLOV2OnXrcqzwbGmFZzM0Ly6xBNyrHqe+pVWdS9kBVjveMfn+9AkOorSa8EzHURUXuGdxJvGB6KkWAM5mKDPOMjcy6I2ifFV/CZ8sshiNK+hITdjVE3A/HQFHm+zK2Duc908qFO2xVg0yD4LPrrXRm282DUgRymSgWHl5tF4v0YMceUZRKy8OmyjFhfMZWhzJwdxk1tMbnwZsNHP35qPWS/2B5FOO6O7e69TtP0FzBqgkWF4QYvwDNXvc4aFIbiBFM3EtYuIqTtwngP9ij0pvkvOZpG1I4ALk5wZdcwWDMUUX60GBai20PEAy8,iv:UCTMZXE+YaT+QFjvs/ZKu9DkWOqxkvrtMWq9nzZm7Fo=,tag:lDP8mEktWIejLnTCcnxlew==,type:str]
    identity.pub: ENC[AES256_GCM,data:E6aKNIgdIuzjA/gUsy6I8VycgjCtl7rggOAjovQfssoOnpBDAbe6tV7xyHID1yFeQG3/ydN9Q25kTPkBG3qTew0yEbJ9m/3ZOvVpfEACl9AR5cK8P5pvZnGqjdbOce4DLhbQ5zMrVjDRuw6t1/gR8OqfwHy/SXtKXD64cHZ3rAXXm26oVYwBamWY44fNADolIXL9AHScQi541XyTqt+kCM8r8nlDnPCjg1EP87lPX/CPmUv5pkGqrR1NR1nKPwxr6AX6TIfDX66QFJeccQ==,iv:kzly5B7VMH9w7Qaxc4VPq6dW5lksdKWy4ISx0/q8zlg=,tag:Um2auq6KS9qfVuI5osvbZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:IJy0siiWnCoFgTiTS/Mr2aSj8iRC8v0Np7/XDZl3GvmGLUglbgxXxZbLivv14pj9OjMN9TifTtXkMBlyZsQ6GDhzYX44qC4Lrz5PeqUhjNzjKiMfUOki4m54QEK4AOOCxq1TKB3V1rzm3VGVapMpryKYE/L2//eYP3dTt5RrW7zb+1wagSDyySf2CSlJ5sn7flT5UJODYHsfvCn2DAde9FSGZpLwQQIQszM1,iv:EFfS108Zxd3HQQZngkp9WBbG2BNt8Q2LSydY39/euAw=,tag:Bsk0BnBD8hnmHXFk2yXzPQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dGJBOFIrMXIwc2pSNExa
            VFZnaHR4bytjNkQ1ZnQrRzEyRXkzeU50L2xvClBLdk5DSnd0TW9KSE1kTFZWbk5M
            ZWQwSTYvc29GYmFJbkdwcXFvRUtNbWsKLS0tIEk2dk8vR0lOdENmTlVqcGFoMWVl
            eFZHVDZ2blljT1RVM3VFaTdmVndYYWcKfo2MVIe1Zl7jUBWFw8U/axb9QdYOTJcJ
            cyu/Xze6yLHZVZjvDtVmY0iC/xMB2UyafO4rJAAFTaWxFGH6uzo7XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T13:04:41Z"
    mac: ENC[AES256_GCM,data:zKrGiuKQAIzh9fTRgkILaE09df6obxSf47qMfC4l76Vfo+kl9zICgeNLmrNvzGWLOzjTob7c/x2f1BrXWR1uEanUF/q/tnGNByhzeSj99Sek2Z+/c3BezMM3kKCX/4mV8mDBSw2h332fZozC5VBO2MAYVRW8TvCHSMptS7xc+8g=,iv:3DA/bvA3QMpP4qveEQ3+JZxUtO51hJbhoQj0uSIQrCo=,tag:Apr3wf+yPFFRtJkwXhherw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
