apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YO+VwJKbnIW4GBMg0SQt5wBxWjJ2ToeETuhrMb2Z75e6PSQ8y/CgCApissNJ9ThOGz17/HF/vxLr/od4Xa4dQH2VpxWQi1NVCLwU11tyHRTyagidrPYMaWrDFRgAHY60UHcfgya69IglUfrZgIWAqQO2w5PEyqFo+fmCUAsqx7uIxwwDaAHysvwbYsaNdv7agPyAroLEcw9u/tZa4U+0UPQmccKoitSLEeWZvTrEovQDF7+f3dN7/k5HF8lbYqPL6+cCaKDLFLkvxPkwbYIKlD3kDXJ5w/YgbXipNfMX1EgKgtleUcD9RqnOjz2pslgQUMjnC9g6qtL8vZr5RPZJco2PEzWqfRkWwbNHrRteeOG1MYYx7uIqfp9u5PjidSek,iv:kWP/Ej54EneLFppaTx8Et1GRhXj+xuYg20IXmmxMMvg=,tag:XME0gYKib9lTmdhYA3jQlw==,type:str]
    identity.pub: ENC[AES256_GCM,data:1773nMfOU6p+vcgKD+obTA8S6EXUuxNc+igST8RhJir7ko33pR9Z1tKz9R9Sl/H0mREH/m/JpZLVoXeDTRfnqFpIveykEWf6Yb/Sz9Gb/h1whbFKMkSb2RLCCOzy7imQ0xxtFNO3Hvq0MOX799fJQ/DzksRUqgtzroCA2mLmhdkzZxIkYXb/YyBqMyIlM5BxL8PKSx/yIL01m8lxtbe+ZNrhWuTFRmp/AlL5z4Eaed6Qd9tpBjtMCoiOsWYBgHFQc9l84HpNJUZPAw9uKw==,iv:RNVlobu/lzfgWIfMDCMMRj3oMXiCLy2XNaQabsuz+sQ=,tag:SfnfkWXsVk/UrDSFVXL0Cg==,type:str]
    known_hosts: ENC[AES256_GCM,data:t8LZz3Xa4oUYu4DJobzctDd3+W08aMDriYYjGQK/F55WiiP23ivo5DtJtE+VkMn/HFWwoibM7rspfXOMMGqJc0+fE7oOZVDhVj0v+WR2rQzEx204p9U2RKyONgz5HCjtqK7ObvipHk97pXMcshJAfiB82w8ub64JkD1ylarLL8q9axRHuBpH+mSdmivmJreq5IeCrpTZyRBqOtwtDBDXMKb0xyTmZYP5xnnQ,iv:GbEKeN7xf6TQaJ5ADhlWxbYO07zL1dYqm5/vDzvjq/0=,tag:OS02uJrtApgfoJysblI47Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cjJqbzJvblF0aWNmbm4v
            VkJrOXdnWU5wbU4vekVoOGdXTXZ4dGZ4c0I4CjEzQ1RxNDdqR043b2pjL0oyTG1x
            M3JkWS92amUvTjhyNUFGOEgrb2w3UUUKLS0tIHBUZ240SU9XM1pnTEZDVTVaUFlD
            T0ZqVktraElPUU5YbHM4TnltaGNaNmcKkGice4xYQjheC9QWgsQlOv8bZ9iuJ39n
            OadVH7z5W6ShFBVwYwb1eLsUSqnP49HwpJsGNrhr3YIOqAcG5cIhJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-15T03:37:14Z"
    mac: ENC[AES256_GCM,data:7UBOrwAupAsZa2XlgDvuakl0zFEu4m0M6fhEB3bPJTE0M8ss/KryvXhM77PrLNKFtWm7QHamhYTBuw0/9tAH5IrOTng4APPSGdNAWqslQ1YdHBYlbAj3lldPeXu1fQwrBgb2idnRFyNVsRw8IfLcr2b4z4NwuCFHHw4TzuiRyYg=,iv:wbt/10OqimORvvw2cUXLShupGTZr6FcXy+j/1Khh5pI=,tag:JLaUOPf7l6Bsdne62vEERA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
