apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UZBgmE+c2sDWu2PYryHKJ4JG2A/Bohi6tmOdNhs4GsW9SqacRADPw9OLbbbZ5RJDroslXoR/oo+el/iB8GckiGTXm/1/wc8rC9ZsQYf6GhaD2+3ohSHLLAfAg7SICw+rvJGOk/RTIeJQ3CbVUQpcOhjyLyBgMWy2CL7+csrD15MG2ZZyKGjUhXkRTOe1/N72LbCEBo1uTvThZcstRDctGEUFQuuOHPZmgcE/khwIp1TDAZSJF1OzQNIqCU2GtOz8G0H9Om5CXAiqDP3rzJRLKHKvbrRZMh690X/FTmLSRxloBNy82QuvPrqVKIEiS2PhVazTWCEAaie1dyqg+McrlYGfD4iTVYx0KFkZTTUXaJx/vGAv54VP3V84JLodGQkQ,iv:hPVD3V2k8RxURFZlTkVNyR8Uh2EjyK+/3501Pt+o5Uw=,tag:dZG61HuUWmnZDIu7SuM0ng==,type:str]
    identity.pub: ENC[AES256_GCM,data:C27+pGXVf8AKYP4vZ//MdMJoKc1WDRmw6NqWcX1yQa0OakXcv9yW2qYs1v9oQbKOExDF5k5NSwY4+IV7OfTqnqvTYTskQTQ0k7LPiiUXj1JaAild54w9w1MJpiho2CM0/gPHCvDesCC2VW0NLZuCwFArHadRyA/b9jI8XLbHyJDukIU9pAZa7KPevBchR+wkOUgTv6aquNkyhlE+DDfa1TATkxwDLIxQb3NQdBmono+Ude9KykDXSJ9Tyq3mpfo9ohBQXqhQUzai6Owp5A==,iv:9BpKnzzCj6uxEPkz6tBeWCyTBoUOjpHzqpPBOt+T7XI=,tag:dJ6xqMUK4Ldy3EiOjnqidA==,type:str]
    known_hosts: ENC[AES256_GCM,data:qPuCLrgSoe7Ibxp3AN1UOK8KG6d1BmOoai/n1WdbTDVRMMLqqQAgrprW9iAXsPiNqn4GwDIvM7mKzC7oAkL76p2R5oiddDXGIF1dm1nHgPGRme47wGj0dOcmgaEcW1zexYbaTqLIAJPOLaF0P7LIVA1xSj2CbHxkRpBonFOIWtChur15pNyy3IxjfgsXR3DJdbxdx3+b4fgmdmTF9/snNO76qjhPvkrVWavt,iv:uwE4k+hyY5nZ2MumXs9eY9xN24WJ6EGia4vBGr7hTQE=,tag:375+PF0K2S4WyG52qNhnMg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdHMvN3R5TEdkVCtFc1ZM
            NFFoS3dUeHpKc2w2SzhXM1J4dU4rY3dkeUIwClU3UmNiTlRUZFJiUWJxTjE3N2FX
            U2Fsak9ldXFQdllBZlpJeWZXN1BENzQKLS0tIHpCYjBQL2wySlhpVm1IV3JFWkpQ
            a1EyQXRuYkExN1lhTmpFWmM3d0E3cHMKuw6tR4RfWnhdNEx1EPiSod3EAxApXQu1
            VQnGgGm7CGN7C9MPknRYb/+/IKfXlUj3+L5wb+d0nqXsgjSCn/t81A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T01:52:17Z"
    mac: ENC[AES256_GCM,data:guAO+MOERoxyLOKHdiWZSvAY/pEyKNMfipYR1ixYyGoFTUgkBv+Ht5/eo8C32WOAfHhWEjrqhQTe+oxUh3inM+UryTRtt3yHiLzS5Q/MTI7WhCGVcjHhmvgvpNhLhPCdSqKmcceZ0AOCEgYbRGKYR9qLnol+o55HpGsuu7VCbKs=,iv:xfX14LsJsFcgo6rCPaeLn/g3CHH2VtnuJVJXWs1MmZQ=,tag:2DnTb4rJDDF+gtG3Bp1oeA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
